name: Hello World matriz

on: [push, workflow_dispatch ]

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: Echo text
              run: echo "Hello, world!"

            - name: running on ${{matrix.os}}
              run: docker ps -a


