name: my first workflow

on: [push]

jobs:
    first_job:
        runs-on:    ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: welcome message
              run: echo 'hello'

            - name: first_file
              run: ls

            - name: read_file
              run: cat README.md

        
